#+title: 百科知识
#+author: 比克曼
#+latex_class: org-latex-pdf 
#+latex: \newpage 

* 百科理工
** GPS
- 地球经纬线：地轴是一根通过地球南北极和地球中心的假想线，在地球中腰画一个与地轴垂直的大圆圈，使圆圈的每个点都和南北极的
  距离相等，这个圆圈就叫做“赤道”，在赤道的南北两边，画出许多和赤道平行的圆圈叫纬线，赤道定为纬度零度，向南向北各90°，
  北极就是北纬90°，南极就是南纬90°；从北极点到南极点，画出许多南北方向的与地球赤道垂直的大圆圈，叫做经度，国际上规定以
  通过英国伦敦近郊的格林尼治天文台的经线作为计算经度的起点，即经度零度零分零秒，也称“本初子午线”；在它东面的为东经，共
  180度，在它西面的为西经，共180度；因为地球是圆的，所以东经180度和西经180度的经线是同一条经线；规定180度经线为“国
  际日期变更线”。为了避免同一地区使用两个不同的日期，国际日期变线在遇陆地时略有偏离；每一经度和纬度还可以再细分为60分，
  每一分再分为60秒以及秒的小数。利用经纬线，我们就可以确定地球上每一个地方的具体位置，并且把它在地图或地球仪上表示出来；
  经度和纬度都是一种角度。
- 经度: 是个两面角，是两个经线平面的夹角。因所有经线都一样长，为度量经度选取一个起点面(本初子午线),本初子午线平面是起点
  面，终点面是本地经线平面,某一点的经度，就是该点所在的经线平面与本初子午线平面间的夹角。
- 纬度：是个线面角。起点面是赤道平面，线是本地的地面法线。所谓法线，即垂直于参考扁球体表面的线；某地的纬度就是该地的法线
  与赤道平面之间的夹角。纬度数值在0至30度之间的地区称为低纬地区，纬度数值在30至60度之间的地区称为中纬地区，纬度数值在60
  至90度之间的地区称为高纬地区。
- ECI坐标系：地心惯性坐标系，earth centered intertial，用于描述卫星的位置，坐标系固定不变；
- ECEF坐标系：地心地球固连坐标系，earth centered，earth fixed，用于描述地面接收器的位置，随着地球自转而旋转，在具体定位
  时，需要将卫星的ECI坐标系的位置转换成它在ECEF坐标系的位置；
- 星历表：本来用来记录天体特定时刻的位置。而在GNSS中，星历表则记录了卫星的运行参数，它使的我们通过星历表就可以计算出任意
  时刻的导航卫星的位置和速度，其数据量较大，传输时间长，也有简版星历表叫历书；
- 历书：包含卫星的位置等信息；
*** GPS组成
**** 空间段
空间段由GPS卫星组成；
**** 控制段
控制段用来控制和监视GPS的运行，控制段包含
- 主控站：
- 监控站：
- 地面控制站：
- 地面天线
**** 用户段
- 民用用户：提供标准定位服务；
- 军用用户：提供精密定位服务；
**** GPS通信信号
GPS通信频率都位于L频段，共有3个频率；
- L1频率：中心频率为1575.42MHz，传输民用的CA码，军用的P(Y)码；
- L2频率：中心频率为1227.6MHz；
- L5频率：中心频率为1176.45MHz, 主要为航空安全服务；
GPS信号包含几个部分
- 测距码：用来测量卫星和接收器间距离的信号，其本质是精心设计的伪随机噪声，也就是上面提到的民用CA码和军用P(Y)码；
  1. CA码：频率F=1.023MHz，周期T=1ms，码长N=1023，码元宽度L=293.05m，测距精度2m到3m，光速为C，码长表示周期范围内有多少个
     脉冲码元，N=F*T，码元宽度计算公式； $$ L = T*C/N $$  
  2. P(Y)码：频率10.23MHz，周期7天，码长6.1871*10^12，码元周期0.097752us，码元宽度为29.3m，测距精度为0.3m，对P码加密后就
     是Y码；
- D码：也叫导航电文，星历和时间信息就封装在导航电文中，其基本单位是帧，一帧包含1500bit，其传输速率为50bit/s，所以传输完
  一帧需要30s, 一个完整的GPS导航电文包含25帧，具体某颗卫星的数据(GPS时间+星历数据)包含在帧的最开始部分，所以每隔30s就可
  以得到更新，共37500bit=4688byte=4.7k，所以传输完需要12.5分钟, 导航电文帧数据内容见表  
  \ref{tbl-dcode}；  
  #+caption: 导航电文内容
  #+label: tbl-dcode
  #+attr_latex: placement=[H]
  |-------------------------+--------------------------------------|
  | 帧                      | 数据                                 |
  |-------------------------+--------------------------------------|
  |-------------------------+--------------------------------------|
  | 1~25                    | 发送卫星的时间等信息                 |
  | 1~25                    | 发送卫星的星历数据                   |
  | 1, 6, 11, 16, 21        | 保留                                 |
  | 2, 3, 4, 5, 7, 8, 9, 10 | SV-25到SV-32的历书数据               |
  | 12，19，20, 22, 23, 24  | 保留                                 |
  | 13                      | NMCT导航电文改正表                   |
  | 14, 15                  | 保留                                 |
  | 17                      | 特殊消息                             |
  | 18                      | 电离层参数和UTC数据                  |
  | 25                      | 32颗卫星的配置情况以及卫星的健康状况 |
  | 1~24                    | SV-1到SV-24的历书数据                |
  | 25                      | SV-1到SV-24的健康状态和历书参考时间  |
  |-------------------------+--------------------------------------|

*** 时间系统
- 国际原子时钟：IAT，international atomic time；
- 协调世界时钟：UTC，coordinated universal time，互联网使用的网络时间协议(NTP)，获取的时间就是UTC，格式年月日时分秒；
- GPS时间：GPST，gps time，以IAT时钟为准，时间原点定于1980年1月6日0时；
- 本地时间：local time, 基于UTC时间，将全球分为24个时区，每个时区的中心为相隔15度经线，第一时区的中心位于子午线；
*** GPS定位
纯粹利用GPS卫星做的定位，叫autonomous模式定位，为了加快定位速度，还可以采用AGPS模式定位，在没有卫星信号时还可以采用移动
蜂窝定位；
**** 定位原理
- 定位：GPS定位时，需要求出接收器的笛卡尔坐标系下的坐标(x, y, z), 已知的东西有如下，但是卫星的时间是精确的同步的，而接收
  器的时间不够精确，这样在第二点上计算的距离就有误差，这个误差是由时间差t导致，这样就出现了4个未知数，本来一个三维坐标系
  只需要3个卫星通过距离公式就能确定，现在有4个未知数了，所以需要4个卫星的距离公式，这样组成一个方程组，4个方程组，就能解
  出4个未知数，这样接收器的笛卡尔坐标系(x, y, z)就能获得，然后再转换，就能得到地球经纬度的位置；
  1. 卫星自身的坐标，通过坐标系转换可以由卫星的坐标系转换到接收器的坐标系；
  2. 卫星到接收器的距离，通过测距码的无线电波速度和传输时间可以算得；
- 速度：根据多普勒效应，无线电波实际的传输频率和接收器以一定速度运动时接收到的频率是有一定关系的，由于GPS卫星的速度可以
  根据导航电文的信息计算得到，频率也已知，而接收器接收到的频率可以测量得到，这样就可以根据多普勒效应频率和速度的关系，推
  导出接收器此时的速度；
**** 定位精度影响
定位精度的影响因素有
1. 卫星时钟：虽然卫星的时钟精度已经很高，但是由于光速的值太大，就造成时间上误差10ns，距离上误差3m；
2. 卫星本身的轨道位置：卫星在轨的位置精度在5m左右；
3. 光速：GPS信号从卫星到地面接收器传输时其速度不是固定值而是会受到电离层，对流层等的影响；
4. 接收器的时钟：接收器时钟和卫星时钟不同步；
5. GPS信号的多路径效应：其他建筑物和物体的反射等；
**** 首次定位时间
首次定位时间(TTFF), time to first fix, 描述的是GPS接收器需要花费多长时间来捕获GPS卫星信号并计算出自己的位置，因启动模式
不同可以分为3种情况；
- 冷启动模式：GPS接收器没有保存有效星历、时间及位置信息，它需要从周围可搜索到的GPS卫星那里接收信号并获取用于定位的数据，
  而一个完整的GPS导航电文需要12.5分钟传输，信号非常好的情况下，所以TTFF至少需要12.5分钟；
- 暖启动模式：GPS接收器保存有星历数据(不超过180天)，旧时间信息(不超过20秒)及旧位置信息(不超过100公里)，但星历数据失效(超
  过4小时)，在计算位置时，需要从卫星处获取到星历数据，但是星历数据在每帧导航电文都有，而一帧传输时间为30秒，所以在这个模
  式下，TTFF至少30秒。
- 热启动模式：GPS接收器具有有效的星历数据，时间，位置等信息，GPS接收器无需解码GPS导航电文中的星历数据，它只要利用GPS信号
  进行测距计算就可以了，此时速度最快，TTFF可以做到10秒以内；
**** AGPS
AGPS就是通过本地网络下载星历数据，从而减小等待时间；AGPS需要在全球建造一个用于收集GPS卫星数据的参考网络，对卫星做跟踪，
比如IGS组织，其[[http://igscb.jpl.nasa.gov/][官网]] 提供GLONASS和GPS的卫星数据下载服务, AGPS将收集到的这些数据放在服务器上并对外提供下载，支持AGPS的手机
就可以通过网络发起下载请求；手机利用AGPS进行定位的方式有
1. MSB模式：手机从AGPS服务器上下载辅助数据，然后手机在结合GPS卫星信号进行定位计算，这种方式需要手机下载辅助数据，同时需
   要利用自身的CPU等资源进行定位计算，这样网络负担小定位延时小，适合短时间内的连续定位；
2. MSA模式：手机接收并解调GPS卫星信号，然后将这些伪距信息传给AGPS服务器，服务器根据这些数据，自己保存的卫星数据以及手机
   当时通信的基站位置计算出所在位置，然后将该信息返回给手机；此模式下，手机无需使用自己的CPU等资源来计算，这样对手机的性
   能要求低，但是定位延迟大，不适合高速行驶时的定位；
**** 网络定位
某地区的移动通信基站或者无线网络AP的位置信息都已经事先获取并保存在相关服务器上，当手机使用网络定位时，手机首先向服务器查询
自己所连接或搜索到的基站或AP的位置，然后根据信号的强度推算自己的大致位置，相比GPS定位，网络定位速度快，耗电少，但精度低；
*** 经纬度转换
- 度转度分秒
  如何将度(DDD)：108.90593度换算成“度分秒(DMS)“，东经E 108度54分22.2秒?转换方法是将108.90593整数位不变取108(度),用
  0.90593*60=54.3558,取整数位54(分),0.3558*60=21.348再取整数位21(秒),故转化为108度54分21秒. 
- 度分秒转度
  同样将度分秒(DMS):东经E 108度54分22.2秒 换算成度(DDD)的方法如下:108度54分22.2秒=108+(54/60)+(22.2/3600)=108.90616度；
  因为计算时小数位保留的原因，导致正反计算存在一定误差，但误差影响不是很大。1秒的误差就是几米的样子。 
*** 经纬度转换米
- 子午线总长度大约L=40008km；
- 赤道半径 = 大约6378.140km；
- 极半径 = 大约6356.755km；
- 地球平均半径 = 大约6371.004km；
- 纬度1度 = (L/2)/180=大约111km ;
- 纬度1分 = 111km/60 = 大约1.85km ;
- 纬度1秒 = 1.85km/60 = 大约30.9m;  
*** 任意两点的经纬度计算两点距离
地球是一个近乎标准的椭球体，它的赤道半径为6378.140千米，极半径为 6356.755千米，平均半径6371.004千米。如果我们假设地球是
一个完美的球体，那么它的半径就是地球的平均半径，记为R。如果以0度经线为基 准，那么根据地球表面任意两点的经纬度就可以计算
出这两点间的地表距离（这里忽略地球表面地形对计算带来的误差，仅仅是理论上的估算值）。设第一点A的经 纬度为(LonA, LatA)，第
二点B的经纬度为(LonB, LatB)，按照0度经线的基准，东经取经度的正值(Longitude)，西经取经度负值(-Longitude)，北纬取90-纬度值
(90- Latitude)，南纬取90+纬度值(90+Latitude)，则经过上述处理过后的两点被计为(MLonA, MLatA)和(MLonB, MLatB)。那么根据三角
推导，可以得到计算两点距离的如下公式：
#+begin_src c
    C = sin(MLatA)*sin(MLatB)*cos(MLonA-MLonB) + cos(MLatA)*cos(MLatB)
    Distance = R*Arccos(C)*Pi/180
#+end_src
这里，R和Distance单位是相同，如果是采用6371.004千米作为半径，那么Distance就是千米为单位，如果要使用其他单位，比如mile，
还需要做单位换算，1千米=0.621371192mile; 如果仅对经度作正负的处理，而不对纬度作90-Latitude(假设都是北半球，南半球只有澳
洲具有应用意义)的处理，那么公式将是： 
#+begin_src c
    C = sin(LatA)*sin(LatB) + cos(LatA)*cos(LatB)*cos(MLonA-MLonB)
    Distance = R*Arccos(C)*Pi/180
#+end_src
以上通过简单的三角变换就可以推出。如果三角函数的输入和输出都采用弧度值，那么公式还可以写作：
#+begin_src c
C = sin(LatA*Pi/180)*sin(LatB*Pi/180) + cos(LatA*Pi/180)*cos(LatB*Pi/180)*cos((MLonA-MLonB)*Pi/180)
Distance = R*Arccos(C)*Pi/180
#+end_src
也就是：
#+begin_src c
C = sin(LatA/57.2958)*sin(LatB/57.2958) + cos(LatA/57.2958)*cos(LatB/57.2958)*cos((MLonA-MLonB)/57.2958)
Distance = R*Arccos(C) = 6371.004*Arccos(C) kilometer = 0.621371192*6371.004*Arccos(C) mile = 3958.758349716768*Arccos(C) mile
#+end_src
在实际应用当中，一般是通过一个个体的邮政编码来查找该邮政编码对应的地区中心的经纬度，然 后再根据这些经纬度来计算彼此的距
离，从而估算出某些群体之间的大致距离范围(比如酒店旅客的分布范围-各个旅客的邮政编码对应的经纬度和酒店的经纬度所 计算的距
离范围-等等)，所以，通过邮政编码查询经纬度这样一个数据库是一个很有用的资源。 附：C#代码： 
#+begin_src c++
private const double EARTH_RADIUS = 6378.137;//地球半径
private static double rad(double d)
{
   return d * Math.PI / 180.0;
}

public static double GetDistance(double lat1, double lng1, double lat2, double lng2)
{
   double radLat1 = rad(lat1);
   double radLat2 = rad(lat2);
   double a = radLat1 - radLat2;
   double b = rad(lng1) - rad(lng2);
   double s = 2 * Math.Asin(Math.Sqrt(Math.Pow(Math.Sin(a/2),2) +
    Math.Cos(radLat1)*Math.Cos(radLat2)*Math.Pow(Math.Sin(b/2),2)));
   s = s * EARTH_RADIUS;
   s = Math.Round(s * 10000) / 10000;
   return s;
}
#+end_src

* 百科经济
** 基本概念
- 利率：储蓄存款利率由国家统一规定，人民银行挂牌公告。利率也称为利息率，是在一定日期内利息与本金的比率，一般分为年利率、
  月利率、日利率三种。年利率以百分比表示，月利率以千分比表示，日利率以万分比表示。如年息九厘写为9%，即每百元存款定期一年
  利息9元，月息六厘写为6‰，即每千元存款一月利息6元，日息一厘五毫写为1.5，即每万元存款每日利息l元5角，目前我国储蓄存款用
  月利率挂牌。为了计息方便，三种利率之间可以换算，其换算公式为；
  1. 年利率÷12=月利率
  2. 月利率÷30=日利率
  3. 年利率÷360=日利率
- 计息起点：储蓄存款利息计算时，本金以“元”为起息点，元以下的角、分不计息，利息的金额算至分位，分位以下四舍五入。分段计
  息算至厘位，合计利息后分以下四舍五入；
- 存期计算规定：
  1. 算头不算尾，计算利息时，存款天数一律算头不算尾，即从存入日起算至取款前一天止;
  2. 不论闰年、平年，不分月大、月小，全年按360天，每月均按30天计算;
  3. 对年、对月、对日计算，各种定期存款的到期日均以对年、对月、对日为准。即自存入日至次年同月同日为一对年，存入日至下月
     同一日为对月;
  4. 定期储蓄到期日，如遇例假不办公，可以提前一日支取，视同到期计算利息，手续同提前支取办理。
- 计算利息基本方法：由于存款种类不同，具体计息方法也各有不同，但计息的基本公式不变，即利息是本金、存期、利率三要素的乘积，
  公式为：利息=本金*利率*时间.如用日利率计算，利息=本金×日利率×存款天数，如用月利率计算，利息=本金×月利率×月数；
  1. 计算过期天数的方法：过期天数=(支取年-到期年)×360+支取月、日数-到期月、日数
  2. 计算利息的方法：
     + 百元基数计息法。适用于定期整存整取、活期存单式储蓄种类的利息计算。
     + 积数计息法。适用于零存整取储蓄利息的计算，也可用于计算活期存折的利息。
     + 利余计息法。适用于活期存折储蓄利息的计算。
- 各储蓄种类的利息计算：
  1. 活期储蓄存款在办理存取业务时，应逐笔在帐页上结出利息余额，俟储户清户时一次计付利息。
  2. 活期储蓄(存折)存款每年结息一次(每年六月三十日为结息日).结息时可把“元”以上利息并入本金，”元”以下角分部分转入下年
     利息余额内。 
  3. 活期储蓄存款在存入期间遇有利率调整，按结息日挂牌公告的活期储蓄存款利率计算利息。全部支取活期储蓄存款，按清户日挂牌
     公告的活期储蓄存款利率计付利息。
  4. 活期储蓄的利息计算公式, 活期储蓄的本金和存期经常变动，因而，活期储蓄利息的计算比较复杂。但只要掌握一定方法，所有的
     计算问题也就迎刃而解了。　　    
- 固定资产折旧的计算方法：企业一般用年限平均法计提折旧，他是根据固定资产的原值减去残值后的余额，固定资产残值一般按固定资
  产的原值的5%预计，(也可根据实际使用年限预计残值)一般建筑类使用20年，设备类使用15年。公式：固定资产年折旧额=固定资产原
  值-净残值/固定资产预计使用年限，年折旧额除以12=月折旧额；
