#+title: 信号与系统
#+author: 比克曼
#+latex_class: org-latex-pdf 
#+latex: \newpage 


* 线性时不变系统
线性时不变系统简称LTI系统，可以用它对单位脉冲序列的响应(h(n))来表示。
- 离散信号可以由单位冲击响应信号来表示。式子如\ref{equ-sigma}, 其中x[k]可以
  看做常量，\(\sigma[n]\) 是冲激响应。
  \begin{equation}
  \label{equ-sigma}
   x[n]=\sum_{k=-\infty}^{+\infty}x[k]\sigma[n-k]
  \end{equation}
- 傅里叶变化和级数：如果x(t)有一个傅里叶级数表示式\ref{equ-xt}，即x(t)能够
  表示成一组谐波关系的复指数信号的线性组合，那么傅里叶级数中的系数a_{k}确定，
  这对关系式就定义为一个周期连续时间信号的傅里叶级数, 其中周期为T，
  \(w_{0}=\frac{2\pi}{T}\) 
  \begin{equation}
  \label{equ-xt}
   x(t)=\sum_{-\infty{}}^{+\infty{}}a_{k}e^{jkw_{0}t}
  \end{equation}
  系数为式\ref{equ-ak}
  \begin{equation}
  \label{equ-ak}
   a_{k}=\frac{\int_{T}x(t)e^{-jkw_{0}t}\mathrm{d}t}{T}
  \end{equation}
- 频率响应：一个脉冲响应(h(n))的离散时间傅里叶变换称为一个LTI系统的频率响应
  或传递函数.也可以理解为，脉冲响应h(n)对某频率输入信号的响应，输入信号x(n)
  可以表示成\(e^{jwn}\)的级数形式，也代表了x(n)具有一系列频率分量w，求一个
  系统对复指数信号\(e^{jw_{0}n}\)的响应时，输入信号为\(x(n)=e^{jw_{0}n}\),
  该响应由式子\ref{equ-ejwnhn}
  \begin{equation}
  \label{equ-ejwnhn}
  x(n)=e^{jw_{0}n} \Rightarrow h(n) \Rightarrow y(n)=h(n)*e^{jw_{0}n}
  \end{equation}
  因而
  \begin{equation}
  \label{equ-whn}
  y(n)=h(n)*e^{jw_{0}n}=\sum_{k=-\infty}^{\infty}h(k)e^{jw_{0}(n-k)}
      = [\sum_{k=-\infty}^{\infty}h(k)e^{-jw_{0}k}]e^{jw_{0}n} 
      = [F[h(n)]|_{w=w_{0}}]e^{jw_{0}n}
  \end{equation}
  由于输入信号x(n)可以表示成复指数的级数形式，所以x(n)的每个频率分量都可以
  经过h(n)在每个频率上做响应，进而叠加得到x(n)的输出y(n)，式子\ref{equ-whn}
  也说明了输出序列是输入指数序列被系统h(n)在w_{0}频率处的响应修饰后的结果。
  因此一个LTI系统可以在频域表示为式子\ref{equ-frqzone}, 时域y(n)可从
  \(Y(e^{jw})\)用傅里叶逆变换获得。 
  \begin{equation}
  \label{equ-frqzone}
  X(e^{jw}) \Rightarrow H(e^{jw}) \Rightarrow Y(e^{jw})=H(e^{jw})X(e^{jw})
  \end{equation}
** 卷积
如果一个系统的冲击响应为h(n), 表示方式如\ref{equ-hn}，可以理解为由于一个k时
刻的单位脉冲\(\sigma{}(n-k)\)引起的系统响应为h(n-k), 而输入信号x(n)是由k从
负无穷时刻到正无穷时刻的所有冲击\(\sigma{}(n-k)\)叠加，所以x(n)的对于线性系
统的响应也就由从负无穷到正无穷逐个移位出来的h(n-k)叠加而成，写成卷积形式如
\ref{equ-conv}, 从某种意义上讲，卷积的输出结果是和时间没有关系的，所以一般
MATLAB或者python的卷积计算函数都不用带时间信息，只需要输入值序列。
\begin{equation}
\label{equ-hn}
 \sigma{}(n-k) \Rightarrow h(n-k)
\end{equation}
\begin{equation}
\label{equ-conv}
 y(n) = x(n)*h(n) 
\end{equation}
** 傅里叶级数和泰勒级数
傅里叶级数和泰勒级数都是为了将一个函数分解成若干基函数叠加形式。
*** 泰勒级数
一个函数
$$f(x)=1$$ 
它的泰勒展开式是
$$f(x)=1$$ 
函数
$$f(x)=x$$ 
它的泰勒展开式是
$$f(x)=x$$ 
也就是泰勒展开将函数分解成\(1, x, x^{2}, x^{3}...\)等幂级数的和，也就是将一
个函数变成若干个函数的和。展开式在多数情况下有无限项。泰勒展开式见式
\ref{equ-taile}
\begin{equation}
\label{equ-taile}
f(x)=\sum_{n=0}^{\infty}\frac{f^{(n)}(x_{0})}{n!}(x-x_{0})^{n}
    = f(x_{0})+f^{'}(x_{0})(x-x_{0})+\frac{f^{''}(x_{0})}{2!}(x-x_{0})^{2}...
\end{equation}
那么为什么要将f展开成泰勒级数\(f(x)=1+x+x^{2}+x^{3}+...\)，那是因为可以无限细
分得到f在每个点的变化。这类似将3234.352拆分成3000+200+30+4+0.3+0.05+0.002一
样。所谓对函数的无限细分，就是不断求导，得到若干个变化率，从而得到这个函数
到底在各个点变化的有多剧烈。变化就是导数。泰勒级数的每一阶系数就是各阶导数。
所以泰勒级数就是在描述一个函数的各个点的变化情况。
*** 傅里叶级数
傅里叶级数也叫三角级数一般为
$$f(x)=1+sin(x)+cos(x)+sin(2x)+cos(2x)+... $$ 
只有周期函数才有傅里叶级数，非周期函数由傅里叶变换来处理。一个方波信号可以
表示成多个不同频率的正弦波组成。在某种程度上也可以认为方波是各种信号的基，
基于这样的认识有人提出了沃尔什变换。将函数分解成三角函数的和很重要。因为对
于一个周期函数来说，和周期对应的是频率。频率表示周期性变化的快慢。频率可以
表征非常广泛的一类属性。在电子学里，有电容隔直通交。其实这就是电容对电学量，
比如电压和电流，不同频率特性的不同体现。对于频率为0 的电压，被隔断，对于频
率为w的电压，会产生与w 和电压U成正比的电流。所以讲一个信号函数分解成不同频
率的分量就比较好处理问题。那为什么分解时最好用正余弦的频率，因为正余弦函数
是二阶偏微分方程(含有电容或电感等的电路方程)的本征解。另外，世界上只有两类
函数能满足给自己求二阶导还是这类函数本身，仅相差常数系数和正负号，一种就是 
\(e^{x}\)，另一种就是\(sin(x), cos(x)\), 后来又在复数域里统一了这两者即
$$e^{jx}=cos(x)+sin(x)j$$ 
所以，对于一个一般的物理信号来说，它可能不是正余弦函数，但是他们都可以拆成
不同频率的三角函数的组合。重要的是对于某种单频率的三角函数信号，系统对该频
率的三角函数的输入的响应还是同频率的三角函数，只可能有相位前后或者幅度大小
发生变化。这样就是二阶偏微分方程的本征解的含义。\par
我们知道我们要把信号函数展开成三角不同频率的三角函数的和，且系统对某种频率
的三角函数的响应方式还是同频率的三角函数，所以响应也是对这些不同频率三角函
数响应的叠加，这也叫频域分析。傅里叶级数的三角表示公式如\ref{equ-flysj}
\begin{equation}
\label{equ-flysj}
f(x)=a_{0}+\sum_{n=l}^{\infty}(a_{n}cos\frac{n\pi x}{l}+b_{n}sin\frac{n\pi x}{l})
\end{equation}
用这个式子可以表示周期是\(2l\)的周期函数，之所以所有频率都是基频的倍数，是
因为它要符合周期性边界条件。式\ref{equ-flysj}可以简化为式子\ref{equ-flysjj}
\begin{equation}
\label{equ-flysjj}
f(x)=a_{0}+A_{1}sin(w_{1}x+phi_{1})+A_{2}sin(2w_{2}x+phi_{2})+...
\end{equation} 
式子\ref{equ-flysjj}可以把傅里叶级数理解成，把周期函数拆成常数(直流分量)+一
倍频分量+2倍频分量+...
其系数\(A_{k}\)需要通过函数投影计算。函数投影类似向量的投影，一个函数u和一
个函数v的投影计算方式如\ref{equ-fun-dot}, 也就是u和v的内积就是他们相乘，并
在全区间上积分。
\begin{equation}
\label{equ-fun-dot}
<u, v> := \int_{a}^{b}u(x)\hat{v}(x)dx
\end{equation}
而在周期函数里面区间端点[a, b]就是任何一个长度为\(2\pi\)的区间端点。那么如
果把u表示成f(x)，v分别取\(1, sin(x), cos(x), sin(2x)...\)等，就可以得到每
个频率的各自部分的分量大小(因为有积分累加)。为什么就一定能够筛选出对应频率
的所以分量来累加呢，这是因为有完备单位正交基，所谓的完备，就是指用
\(1, sin(x), cos(x), sin(2x)...\)完全能够把一个函数f(x)表示出来。
所谓正交，如式子\ref{equ-zj}两两相乘区间累加都等于0，是正交的。
\begin{equation}
\label{equ-zj}
\int_{0}^{2\pi}1*sin(x)dx=0, 
\int_{0}^{2\pi}sin(mx)*cos(nx)dx=0, 
\int_{0}^{2\pi}sin(mx)*sin(nx)dx=0, 
\end{equation}
所谓单位，就是还需要归一化，比如\ref{equ-notuni}不是归一化的。
\begin{equation}
\label{equ-notuni}
\int_{0}^{2\pi}1*1dx=2\pi
\int_{0}^{2\pi}sin(kx)*sin(kx)dx=pi
\end{equation}
要归一化就得变成如下式子
\begin{equation}
\int_{0}^{2\pi}\frac{1}{\sqrt{2\pi}}*\frac{1}{\sqrt{2\pi}}dx=1
\int_{0}^{2\pi}\frac{1}{\sqrt{\pi}}sin(kx)*\frac{1}{\sqrt{\pi}}sin(kx)dx=1
\end{equation}
所以傅里叶分解真正的基底是这些, 对于周期为\(2\pi\)
$$\frac{1}{\sqrt{2\pi}},\frac{1}{\sqrt{\pi}}sin(x),\frac{1}{\sqrt{\pi}}cos(x)...$$ 
对于周期为\(2l\)的，基底是
$$\frac{1}{\sqrt{2l}},\frac{1}{\sqrt{l}}sin(x),\frac{1}{\sqrt{l}}cos(x)...$$
综合来看，用内积方法分解出的每个分量的系数如式子\ref{equ-neijfly}, 如果是非
单位化的基，结果就没有这么简洁。
\begin{equation}
\label{equ-neijfly}
a_{0} = \frac{\int_{-l}^{l}f(x)dx}{2l}
a_{n} = \frac{\int_{-l}^{l}f(x)cos(\frac{n\pi x}{l})dx}{l}
b_{n} = \frac{\int_{-l}^{l}f(x)sin(\frac{n\pi x}{l})dx}{l}
\end{equation}



** 离散时间傅里叶变换(DTFT)
如果x(n)是绝对可加的，即\(\sum_{-\infty}^{\infty}|x(n)| < \infty\)，则其离
散时间傅里叶变换表示如\ref{equ-xjw}
\begin{equation}
\label{equ-xjw}
 X(e^{jw}) \Rightarrow F[x(n)]=\sum_{-\infty}^{\infty}x(n)e^{-jwn}
\end{equation}
\(X(e^{jw})\)的离散时间傅里叶逆变换(IDTFT)可以表示如\ref{equ-xn}
\begin{equation}
\label{equ-xn}
 x(n) \Rightarrow F^{-1}[X(e^{jw})]=\frac{1}{2\pi}\int_{-\pi}^{\pi}X(e^{jw})e^{jwn}dw
\end{equation}
算子F[.]把一个离散信号x(n)变换成一个实变量w的复值连续函数\(X(e^{jw})\), w被
称为数字频率，它用 _弧度_ 来度量。
*** DTFT算法过程
如果x(n)是有限长的，则x(n)肯定是绝对可加的，即x(n)肯定有DTFT，则可以用
MATLAB或python来对任意频率w处的\(X(e^{jw})\)进行数值计算。如果我们是在
\([0, \pi]\)间等间隔频率点来模拟估计\(X(e^{jw})\)，假设分成M分，则每个频率
点可以表示如公式\ref{equ-wk}所示，则变换式子\ref{equ-xjw}可以用矩阵向量相乘
的运算来实现。
\begin{equation}
\label{equ-wk}
w_{k} \Rightarrow \frac{\pi}{M}k, (k = 0, 1, ...,M)
\end{equation}
假定序列x(n)在\(n_{1}<= n <=n_{n}\)有N个样本，要估计点\ref{equ-wk}上的
\(X(e^{jw})\)值。它们是[0，\pi]之间的(M+1)个等间隔频率点，则\ref{equ-xjw}可
以写为式子\ref{equ-xjw2}
\begin{equation}
\label{equ-xjw2}
 X(e^{jw_{k}})=\sum_{l=1}^{N}e^{-j(\pi/M)kn_{l}*x(n_{l})}, (k=0, 1, ..., M)
\end{equation}
当\({x(n_{l})}\)和\({X(e^{jw_{k}})}\)分别排成列向量x和X，我们有式子
\ref{equ-vec}, 其中W是一个(M+1)乘N维矩阵
\begin{equation}
\label{equ-vec}
 X = Wx
\end{equation}
另外，若我们分别将{k}和{n_{l}}排成列向量，则有式子\ref{equ-wvec}
\begin{equation}
\label{equ-wvec}
 W = [e^{-j\frac{\pi}{M}k^{T}n}]
\end{equation}
最终可以写成式子\ref{equ-fvec}, 如果x是行行向量，则x^{T}直接就用x表示。
\begin{equation}
\label{equ-fvec}
 X^{T} = x^{T}[e^{-j\frac{\pi}{M}n^{T}k}]
\end{equation}
** 滤波器
*** FIR滤波器
如果一个LTI系统的单位脉冲响应长度有限，则此系统称为有限长度脉冲响应(FIR)滤
波器。因此对一个FIR滤波器，在\(n<n_{1}\)和\(n>n_{2}\)时h(n)=0.
*** IIR滤波器
如果一个LTI系统的脉冲响应具有无线长度，则此系统称为无限长脉冲响应(IIR)滤波
器。
